title: Aniekan Inyang # your name (or website title) here
logo: "/images/1688228_1110892445588839_9060117836842109834_n.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I am Aniekan, a Computer Science gradute with interests in natural language processing and machine learning.
  <br><br>
  I have over 2+ years experience in the Data Science industry with expertise in data analytics and visualisation drawing insights from data, 
  topic modelling, text analysis and classification. 
  <br><br>
  <a href="https://www.linkedin.com/in/aniekan-inyang/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
