title: Aniekan Inyang # your name (or website title) here
logo: "/images/1688228_1110892445588839_9060117836842109834_n.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist and Python dev with interests in NLP and Predictive Analytics/Modelling.
  <br>
  With industry and research skills in natural language processing and machine learning, I aim to enable organisations to use data to understand people better, optimise processes, and make better decisions. 
  I have experience in data analytics and visualisation to draw insights from data, text classification and analysis, topic modelling. 
  I am also very passionate about raising and mentoring a community of girls and women in Data Science and Artificial Intelligence.
  <br><br>
  <a href="https://www.linkedin.com/in/aniekan-inyang/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
